# Generated by Django 4.1.7 on 2024-01-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test1', '0003_alter_place_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200)),
                ('timg', models.ImageField(upload_to='team')),
            ],
        ),
    ]
