# Generated by Django 4.1.7 on 2024-01-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test1', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='reviw',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
